### ISSUE TITLE
Create pre-commit check

### ISSUE THREAD

**Issue by spookylukey** [AliSayyah/django-urlconfchecks#37]
One of my colleagues suggested the possibility of running this project as a [pre-commit](https://pre-commit.com/) check. Worth doing?

**Comment by spookylukey** [comment]
Actually I'm not sure that would work well. Feel free to close this unless you can think of a good way.

**Comment by AliSayyah** [comment]
Thanks for the suggestion; I'll check into it.
What additional value would that add?

**Comment by spookylukey** [comment]
I guess the advantages would be:
- possibly easier installation, because people are used to pre-commit
- possibly better/faster at catching issues, because some people might not be running `manage.py check` as part of their normal workflow, or `manage.py runserver`, or they are running it in a window where they don't see it.

Another option is to run as some kind of mypy plugin, which would work really well for people who use mypy checks as instant feedback. See https://mypy.readthedocs.io/en/stable/extending_mypy.html

I'm just thinking out loud here, I'm not sure what the best options are.

**Comment by AliSayyah** [comment]
Thank you for this thorough explanation.
These are valid points.
Especially I liked the mypy plugin system.
I'll add these to the to-do list for further exploration.

**Comment by AliSayyah** [comment]
@spookylukey Hi there!
The package now has a CLI tool and also supports pre-commit hooks.
