### ISSUE TITLE
Ignore warnings for admin endpoint

### ISSUE THREAD

**Issue by nightboard** [AliSayyah/django-urlconfchecks#67]
I think I am getting warnings in the `admin` endpoint so can we add a feature that will ignore warnings for `admin.site.urls`?

**Comment by AliSayyah** [comment]
Hey there!
Yes, that's correct. I'll fix it as soon as I get back from vacation.
Thank you for reporting this.

**Comment by nightboard** [comment]
@AliSayyah No can I work on this issue If you can just give me a hint of which files I need to change or anything that can help me I never contributed to any open source project yet.

**Comment by AliSayyah** [comment]
Yes, of course. In the `check.py` module, you can probably achieve what you want by changing the `get_all_routes` function.
If you have any problems, don't hesitate to ask.

**Comment by nightboard** [comment]
@AliSayyah  Thanks you can assign this issue to me I will start working on this.

**Comment by AliSayyah** [comment]
Also, we can have a mechanism for excluding URLs that the user doesn't want. It can be used to achieve something like `urlconfchecks --exclude User` and we can easily use this to exclude django's internal URLs.

**Comment by AliSayyah** [comment]
Thank you @nightboard for the fix.
This is now closed.
